add_newline = true
command_timeout = 1000

format = """
[╭─](bold cyan)$username$hostname$directory$git_branch$git_status
[╰─](bold cyan)$character
"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](bold yellow) "

[directory]
style = "bold blue"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 200
format = "[⏱ $duration](bold yellow) "

[status]
style = "bold red"
format = "[✖ $status]($style) "
disabled = false

[time]
disabled = false
style = "bold white"
format = "[  $time ]($style)"
time_format = "%H:%M"
