[config]
reload = true

[templates.gtk]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/MatugenTemplates/gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/MatugenTemplates/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.qt]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/MatugenTemplates/qtct.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.hypr]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/MatugenTemplates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.pywal]
input_path = "~/.config/matugen/pywal.json"
output_path = "~/.cache/wal/colors.json"
